[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "setuptools_scm>=6.2"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "deepinv/version.py"
local_scheme = "no-local-version"
fallback_version = "dev"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "deepinv/tests",
]
